services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: aahara
      POSTGRES_USER: atmansanjai
      POSTGRES_PASSWORD: atmansanjai
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
